Query creator
levFarkas/GooglePathFinder pull request #6
Opened 2021-04-26 16:19 UTC by levFarkas

2021-04-27 21:36 UTC, ScalaN22 approved these changes

2021-04-29 09:08 UTC, qellin commented on src/backend/persistence/connector/mysql_connector.py
> +        FROM PATHFINDER.NODES""")
a Selecthez nem elegendő egy Select * From az vissza ad minden attribútumot egy táblából

2021-04-29 20:53 UTC, qellin requested changes
Szia Levi, megtennéd hogy leírod hogy itt mit akartál kérdezni, mert nem tudok rájönni hogy pontosan mit próbálsz lekérdezni, mert ha ez a lekérdezés akkor nem jól látod a táblakapcsolatokat. A másik hogy nem kell kiírni minden attribútumot helyette Select * From ez egy korábbira vonatkozik. Még azt vettem észre hogy egyszer sem kérdezed le az edges táblát pedig az tartalmazza az útvonalak hosszát.
[query_k.txt](https://github.com/levFarkas/GooglePathFinder/files/6401579/query_k.txt)

2021-04-29 20:53 UTC, qellin commented on src/backend/persistence/connector/mysql_connector.py
> +
Szia Levi, megtennéd hogy leírod hogy itt mit akartál kérdezni, mert nem tudok rájönni hogy pontosan mit próbálsz lekérdezni, mert ha ez a lekérdezés akkor nem jól látod a táblakapcsolatokat. A másik hogy nem kell kiírni minden attribútumot helyette Select * From ez egy korábbira vonatkozik. Még azt vettem észre hogy egyszer sem kérdezed le az edges táblát pedig az tartalmazza az útvonalak hosszát.
[query_k.txt](https://github.com/levFarkas/GooglePathFinder/files/6401573/query_k.txt)

2021-05-01 20:07 UTC, merged